resolver: lts-7.22

packages:
- '.'

extra-deps:
- freetype2-0.1.1

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
